users:
- username: "stelevinken"
  comment: "Skel Televinken"
  uid: "1010"
  group: "televinken"
  password: "skel"
  shell: /bin/bash

- username: "skundservice"
  comment: "Skel Kundservice"
  uid: "1011"
  group: "3kundservice"
  password: "skel"
  shell: /bin/bash

- username: "stelesales"
  comment: "Skel Telesales"
  uid: "1012"
  group: "3telesales"
  password: "skel"
  shell: /bin/bash

- username: "ssolsidan"
  comment: "Skel Solsidan"
  uid: "1013"
  group: "3solsidan"
  password: "skel"
  shell: /bin/bash

- username: "tone"
  comment: "Test One"
  uid: "1201"
  group: "televinken"
  password: "111111"
  shell: /bin/bash

