- name: update packages
  apt:
    upgrade: dist
    update_cache: yes
    state: build-dep
    allow_unauthenticated: no
    autoremove: yes

- name: install dependencies
  shell: apt install -fy

- git:
    repo: 'https://github.com/george4n/styx.git'
    dest: /usr/local/bin/styx/
    clone: yes
    update: yes

- name: ltsp initrd
  shell: ltsp initrd
  ignore_errors: true

- name: regenerate boot image
  shell: ltsp image /