- name: "Create user accounts"
  user:
    name: "{{ item.username }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: "always"
    shell: "{{ item.shell }}"     
    create_home: "yes"
    append: no
  with_items: "{{ users }}"